'use client'

import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#FFFAF5]">

      <Navbar />

      {/* CONTENT */}
      <div className="max-w-3xl mx-auto px-6 py-20">
        <p className="text-xs text-[#F4845F] tracking-[0.3em] uppercase mb-3" style={{ fontFamily: 'var(--font-josefin)' }}>✦ Legal</p>
        <h1 className="text-5xl text-[#1C0A00] mb-3" style={{ fontFamily: 'Georgia, serif', fontStyle: 'italic', fontWeight: '400' }}>Terms Of Service</h1>
        <p className="text-xs text-[#8B5E52] mb-12" style={{ fontFamily: 'var(--font-josefin)' }}>Last Updated: June 2, 2026</p>

        <div className="space-y-10 text-[#1C0A00]">

          <div>
            <h2 className="text-lg font-semibold mb-3" style={{ fontFamily: 'var(--font-syne)' }}>1. Acceptance Of Terms</h2>
            <p className="text-sm text-[#8B5E52] leading-relaxed">By accessing or using ZanZan Beauty Studio and its services, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our platform. ZanZan Beauty Studio is owned and operated by ZanZan Beauty Studio LLC. We reserve the right to update these terms at any time and will notify users of significant changes.</p>
          </div>

          <div>
            <h2 className="text-lg font-semibold mb-3" style={{ fontFamily: 'var(--font-syne)' }}>2. Description Of Service</h2>
            <p className="text-sm text-[#8B5E52] leading-relaxed">ZanZan Beauty Studio provides an AI-powered makeup routine builder that analyzes facial features and generates personalized beauty routines. Our service is currently in beta and is provided free of charge. Features, pricing and availability are subject to change at any time without prior notice.</p>
          </div>

          <div>
            <h2 className="text-lg font-semibold mb-3" style={{ fontFamily: 'var(--font-syne)' }}>3. User Accounts</h2>
            <p className="text-sm text-[#8B5E52] leading-relaxed">You may create an account using your email address. You are responsible for maintaining the confidentiality of your account and for all activities that occur under your account. You agree to provide accurate and complete information when creating your account. ZanZan Beauty Studio reserves the right to terminate accounts at any time for any reason, including but not limited to violation of these terms.</p>
          </div>

          <div>
            <h2 className="text-lg font-semibold mb-3" style={{ fontFamily: 'var(--font-syne)' }}>4. Intellectual Property</h2>
            <p className="text-sm text-[#8B5E52] leading-relaxed">All content on ZanZan Beauty Studio including but not limited to the name ZanZan, the ZanZan Beauty Studio logo, website design, code, text, graphics, and the Lumi AI assistant are the exclusive property of ZanZan Beauty Studio LLC and are protected by United States copyright law. You may not reproduce, distribute, modify, create derivative works of, publicly display, or otherwise use any content from ZanZan Beauty Studio without explicit written permission. Unauthorized use of our intellectual property may result in legal action.</p>
          </div>

          <div>
            <h2 className="text-lg font-semibold mb-3" style={{ fontFamily: 'var(--font-syne)' }}>5. User Content</h2>
            <p className="text-sm text-[#8B5E52] leading-relaxed">You retain ownership of any photos or content you upload to ZanZan Beauty Studio. By uploading content you grant ZanZan Beauty Studio a non-exclusive, royalty-free, worldwide license to use, store and process that content solely for the purpose of providing our services to you. We do not sell or share your photos or personal content with third parties. You may delete your content and account at any time.</p>
          </div>

          <div>
            <h2 className="text-lg font-semibold mb-3" style={{ fontFamily: 'var(--font-syne)' }}>6. AI Generated Content</h2>
            <p className="text-sm text-[#8B5E52] leading-relaxed">Beauty routines and recommendations generated by ZanZan Beauty Studio are powered by artificial intelligence and are intended for informational and entertainment purposes only. They do not constitute professional beauty, medical or dermatological advice. ZanZan Beauty Studio makes no warranties regarding the accuracy, completeness or suitability of AI generated content for any individual. Always consult a professional for specific skin conditions or concerns.</p>
          </div>

          <div>
            <h2 className="text-lg font-semibold mb-3" style={{ fontFamily: 'var(--font-syne)' }}>7. Prohibited Activities</h2>
            <p className="text-sm text-[#8B5E52] leading-relaxed mb-3">You agree not to engage in any of the following activities:</p>
            <ul className="space-y-2 text-sm text-[#8B5E52]">
              {[
                'Scraping, crawling or extracting data from ZanZan Beauty Studio without written permission',
                'Attempting to reverse engineer, decompile or access the source code of our platform',
                'Using ZanZan Beauty Studio to build a competing product or service',
                'Uploading content that is illegal, harmful, offensive or violates the rights of others',
                'Attempting to gain unauthorized access to any part of our platform or infrastructure',
                'Using automated tools to access or interact with the platform beyond normal usage',
              ].map((item) => (
                <li key={item} className="flex items-start gap-2">
                  <span className="text-[#F4845F] mt-0.5 flex-shrink-0">✦</span>
                  {item}
                </li>
              ))}
            </ul>
          </div>

          <div>
            <h2 className="text-lg font-semibold mb-3" style={{ fontFamily: 'var(--font-syne)' }}>8. Affiliate Disclosure</h2>
            <p className="text-sm text-[#8B5E52] leading-relaxed">ZanZan Beauty Studio participates in affiliate marketing programs. When you click on product links within our platform and make a purchase, we may earn a commission at no additional cost to you. This does not influence our product recommendations. We only recommend products we believe are genuinely useful for our users.</p>
          </div>

          <div>
            <h2 className="text-lg font-semibold mb-3" style={{ fontFamily: 'var(--font-syne)' }}>9. Limitation Of Liability</h2>
            <p className="text-sm text-[#8B5E52] leading-relaxed">ZanZan Beauty Studio LLC shall not be liable for any indirect, incidental, special, consequential or punitive damages resulting from your use of or inability to use our services. Our total liability to you for any claim arising out of or relating to these terms or our services shall not exceed the amount you have paid us in the twelve months prior to the claim.</p>
          </div>

          <div>
            <h2 className="text-lg font-semibold mb-3" style={{ fontFamily: 'var(--font-syne)' }}>10. Governing Law</h2>
            <p className="text-sm text-[#8B5E52] leading-relaxed">These Terms of Service shall be governed by and construed in accordance with the laws of the United States. Any disputes arising under these terms shall be subject to the exclusive jurisdiction of the courts located in the United States.</p>
          </div>

          <div>
            <h2 className="text-lg font-semibold mb-3" style={{ fontFamily: 'var(--font-syne)' }}>11. Contact</h2>
            <p className="text-sm text-[#8B5E52] leading-relaxed">If you have any questions about these Terms of Service please contact us at legal@zanzanbeauty.com</p>
          </div>

        </div>
      </div>

      <Footer />

    </div>
  )
}
